### ISSUE TITLE
FaceLandmarkImg.exe in windows yields no output

### ISSUE THREAD

**Issue by AndrewBragdon** [TadasBaltrusaitis/OpenFace#314] opened 2018-01-06 05:55 UTC
Followed instructions here:

https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments

I ran FaceLandmarkImg.exe on Windows x64.  It momentarily flashes the recognized image on the screen and then exits.  No "processed" directory is created anywhere with data in it.  I tried running with -out_dir with both a relative and absolute path, still no output directory created.

How can I get the output?

**Comment by TadasBaltrusaitis** [comment] 2018-01-10 20:28
That's odd, are you using the latest code or executable? Version 0.3.0? 

Have you tried running the code to process the data in samples directory? Can you give me the exact command line arguments you used?

Thanks,
Tadas

**Comment by Heyxiang** [comment] 2018-01-18 03:20
I have a same problem   FeatureExtraction.exe -f "C:\my videos\video.avi"     no  output @TadasBaltrusaitis  @AndrewBragdon

**Comment by TadasBaltrusaitis** [comment] 2018-01-18 21:40
Does the video of tracking appear? What is the output in the log?

**Comment by Cloudmersive** [comment] 2018-01-22 03:25
@TadasBaltrusaitis  Yeah I was using the latest code/executable (0.3.0)

Re: command line, I used the exact arguments (and steps) listed here:

https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments

**Comment by AndrewBragdon** [comment] 2018-01-22 03:26
@TadasBaltrusaitis Yeah I was using the latest code/executable (0.3.0)

Re: command line, I used the exact arguments (and steps) listed here:

https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments

**Comment by TadasBaltrusaitis** [comment] 2018-01-23 10:59
Do you mean you used one of the sample commands? It would be helpful with debugging if you provide the exact command used and the console output, as I can't reproduce the issue.

-Tadas

**Comment by karlTUM** [comment] 2018-01-28 08:45
Hi, I also do not have output file on Ubuntu. 
Here is the details:

I run the code: 
`./FeatureExtraction -f /home/karl/Documents/OpenFace/samples/2015-10-15-15-14.avi -out_dir /home/karl/Documents/OpenFace/samples/output_results`

The video of tracking appears, but no output file.


```
./FaceLandmarkVid -f /home/karl/Documents/OpenFace/samples/2015-10-15-15-14.avi -out_dir /home/karl/Documents/OpenFace/samples/output_results -of result1
Reading the CLNF landmark detector/tracker from: model/main_clnf_general.txt
Reading the landmark detector module from: model/clnf_general.txt
Reading the PDM module from: model/pdms/In-the-wild_aligned_PDM_68.txt....Done
Reading the Triangulations module from: model/tris_68.txt....Done
Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.25_general.txt....Done
Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.35_general.txt....Done
Reading the intensity CCNF patch experts from: model/patch_experts/ccnf_patches_0.5_general.txt....Done
Reading part based module....inner
Reading the CLNF landmark detector/tracker from: model/model_inner/main_clnf_inner.txt
Reading the landmark detector module from: model/model_inner/clnf_inner.txt
Reading the PDM module from: model/model_inner/pdms/pdm_51_inner.txt....Done
Reading the intensity CCNF patch experts from: model/model_inner/patch_experts/ccnf_patches_1.00_inner.txt....Done
Done
Reading part based module....left_eye_28
Reading the CLNF landmark detector/tracker from: model/model_eye/main_clnf_synth_left.txt
Reading the landmark detector module from: model/model_eye/clnf_left_synth.txt
Reading the PDM module from: model/model_eye/pdms/pdm_28_l_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/left_ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/left_ccnf_patches_1.50_synth_lid_.txt....Done
Done
Reading part based module....right_eye_28
Reading the CLNF landmark detector/tracker from: model/model_eye/main_clnf_synth_right.txt
Reading the landmark detector module from: model/model_eye/clnf_right_synth.txt
Reading the PDM module from: model/model_eye/pdms/pdm_28_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: model/model_eye/patch_experts/ccnf_patches_1.50_synth_lid_.txt....Done
Done
Reading the landmark validation module....Done
Attempting to read from file: /home/karl/Documents/OpenFace/samples/2015-10-15-15-14.avi
Device or file opened
Starting tracking
Error: Failed to open a sequence
```

@TadasBaltrusaitis  Do you know how to solve this?

**Comment by TadasBaltrusaitis** [comment] 2018-01-29 08:08
It seems like OpenFace is not able to open the video file, could be a codec issue. Can you try running it on images or on other videos? Are you able to play the video file you are processing (2015-10-15-15-14.avi)?

**Comment by karlTUM** [comment] 2018-01-29 17:54
@TadasBaltrusaitis  I can run it on other videos but also cannot produce the output file. The video can be displayed during running the code.

**Comment by TadasBaltrusaitis** [comment] 2018-01-29 18:39
From the log you posted it seems like you are running `FaceLandmarkVid` and not `FeatureExtraction` executable:

`./FaceLandmarkVid -f /home/karl/Documents/OpenFace/samples/2015-10-15-15-14.avi -out_dir /home/karl/Documents/OpenFace/samples/output_results -of result1`

`FaceLandmarkVid` is only intended for visualisation purposes and will not produce an output, for output you need to use `FeatureExtraction`

**Comment by JadonMing** [comment] 2018-02-03 20:31
@TadasBaltrusaitis I was facing exactly the same problem as @AndrewBragdon described. Running in Windows 10 with Visual Studio 2017 and redistributable package 2015.

**Comment by TadasBaltrusaitis** [comment] 2018-02-05 18:31
I'm not able to reproduce this issue, any output from the command line and exact command line arguments would be helpful.

**Comment by TadasBaltrusaitis** [comment] 2018-08-24 16:17
This should be fixed now, re-open if persists.

**Closed by TadasBaltrusaitis** 2018-08-24 16:17 UTC

**Comment by seymatakir28** [comment] 2021-10-29 11:22
@TadasBaltrusaitis I was facing same problem. Problem is 'FileNotFoundError: [Errno 2] No such file or directory: 'output.mp4'
What is mean? I am using colab. How can i solve this problem?
